name: Run Notebook on Schedule
 
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every hour, adjust as needed
 
jobs:
  run_notebook:
    runs-on: ubuntu-latest
 
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
 
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your notebook's Python version
 
      - name: Install dependencies
        run: |
          pip install nbconvert  # For executing notebooks
          #pip install -r requirements.txt  # Optional: Install other dependencies
 
      - name: Run the notebook
        run: |
          jupyter nbconvert --to notebook --execute Table_Validation.ipynb --output output.ipynb
