name: Run Notebook on Schedule
 
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  run-bigquery:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'  

    - name: Install Jupyter
      run: |
        pip install jupyter  # Ensure Jupyter is installed
        pip install nbconvert  # For executing notebooks
        pip install google-cloud-bigquery  
 
    - name: Set up BigQuery credentials
      env:
        BIGQUERY_KEY: ${{ secrets.BIGQUERY_KEY }}
      run: |
        echo "$BIGQUERY_KEY" > bigquery-key.json
 
    - name: Run BigQuery script
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/bigquery-key.json
      run: |
        jupyter nbconvert --to notebook --execute Hive_Bigquery_automation.ipynb --output output.ipynb
